pipeline {
  agent { label 'KtVasquezLabel'}
  environment {
     HOME_DIR = "/Users/katerinluciavasquezmorales/Documents/jenkins"
   }
  triggers {
    gitlab(
      triggerOnPush: true,
      triggerOnMergeRequest: true,
      branchFilterType: "NameBasedFilter",
      includeBranchesSpec: '${GIT_BRANCH}')
  }
  stages {
      stage('Preparation') {
        steps {
          dir('Source') {
              sh 'security unlock-keychain -p "detectidsdk" ${HOME}/Library/Keychains/login.keychain'
              sh 'rm -rf Framework/*'
          }
        }
      }
      
       stage('Update Libraries Simulator') {
        steps {
           sh 'Echo detectidsdk | rsync --delete -avz -e ssh ${HOME_DIR}/workspace/iOS-Data_${GIT_BRANCH}-[a-zA-Z0-9]*/Framework/Simulator/did_sdk_data_ios.framework ${HOME_DIR}/workspace/iOS-DID-SDK_${GIT_BRANCH}-[a-zA-Z0-9]*/Source/DID_Auth_SDK/didm_auth_sdk_iOS/didm_auth_sdk_iOS/external_library/Core/'
           
           sh 'Echo detectidsdk | rsync --delete -avz -e ssh ${HOME_DIR}/workspace/iOS-Encryptor_${GIT_BRANCH}-[a-zA-Z0-9]*/Framework/Simulator/did_sdk_encrypt_iOS.framework ${HOME_DIR}/workspace/iOS-DID-SDK_${GIT_BRANCH}-[a-zA-Z0-9]*/Source/DID_Auth_SDK/didm_auth_sdk_iOS/didm_auth_sdk_iOS/external_library/Core/'
           
           sh 'Echo detectidsdk | rsync --delete -avz -e ssh ${HOME_DIR}/workspace/iOS-Server_${GIT_BRANCH}-[a-zA-Z0-9]*/Framework/Simulator/did_sdk_server_communication_iOS.framework ${HOME_DIR}/workspace/iOS-DID-SDK_${GIT_BRANCH}-[a-zA-Z0-9]*/Source/DID_Auth_SDK/didm_auth_sdk_iOS/didm_auth_sdk_iOS/external_library/Core/'
           
           sh 'Echo detectidsdk | rsync --delete -avz -e ssh ${HOME_DIR}/workspace/iOS-Device_${GIT_BRANCH}-[a-zA-Z0-9]*/Framework/Simulator/did_sdk_deviceInfo_iOS.framework ${HOME_DIR}/workspace/iOS-DID-SDK_${GIT_BRANCH}-[a-zA-Z0-9]*/Source/DID_Auth_SDK/didm_auth_sdk_iOS/didm_auth_sdk_iOS/external_library/Core/'
           
          sh 'Echo detectidsdk | rsync --delete -avz -e ssh ${HOME_DIR}/workspace/iOS-Challenge_${GIT_BRANCH}-[a-zA-Z0-9]*/Framework/Simulator/did_sdk_challengeotp_ios.framework ${HOME_DIR}/workspace/iOS-DID-SDK_${GIT_BRANCH}-[a-zA-Z0-9]*/Source/DID_Auth_SDK/didm_auth_sdk_iOS/didm_auth_sdk_iOS/external_library/AuthFactors/'
          
         sh 'Echo detectidsdk | rsync --delete -avz -e ssh ${HOME_DIR}/workspace/iOS-Offline_${GIT_BRANCH}-[a-zA-Z0-9]*/Framework/Simulator/did_sdk_offline_ios.framework ${HOME_DIR}/workspace/iOS-DID-SDK_${GIT_BRANCH}-[a-zA-Z0-9]*/Source/DID_Auth_SDK/didm_auth_sdk_iOS/didm_auth_sdk_iOS/external_library/AuthFactors/'
        }
      }
      
      stage('Build Simulator') {
          steps {
            dir('Source/DID_Auth_SDK/didm_auth_sdk_iOS') {
              echo 'Building iOS Project'
              sh 'xcodebuild -project didm_auth_sdk_iOS.xcodeproj -scheme didm_auth_sdk_iOS -configuration "Release" -sdk iphonesimulator -destination "platform=iOS Simulator,name=iPhone 8" clean'
              sh 'xcodebuild -project didm_auth_sdk_iOS.xcodeproj -scheme didm_auth_sdk_iOS -configuration "Release" -sdk iphonesimulator -destination "platform=iOS Simulator,name=iPhone 8" ONLY_ACTIVE_ARCH=NO ARCHS="i386 x86_64"'
            }
          }
        }
      
    stage('Update Libraries') {
     steps {
        sh 'Echo detectidsdk | rsync --delete -avz -e ssh ${HOME_DIR}/workspace/iOS-Data_${GIT_BRANCH}-[a-zA-Z0-9]*/Framework/Devices/did_sdk_data_ios.framework ${HOME_DIR}/workspace/iOS-DID-SDK_${GIT_BRANCH}-[a-zA-Z0-9]*/Source/DID_Auth_SDK/didm_auth_sdk_iOS/didm_auth_sdk_iOS/external_library/Core/'

        sh 'Echo detectidsdk | rsync --delete -avz -e ssh ${HOME_DIR}/workspace/iOS-Encryptor_${GIT_BRANCH}-[a-zA-Z0-9]*/Framework/Devices/did_sdk_encrypt_iOS.framework ${HOME_DIR}/workspace/iOS-DID-SDK_${GIT_BRANCH}-[a-zA-Z0-9]*/Source/DID_Auth_SDK/didm_auth_sdk_iOS/didm_auth_sdk_iOS/external_library/Core/'

        sh 'Echo detectidsdk | rsync --delete -avz -e ssh ${HOME_DIR}/workspace/iOS-Server_${GIT_BRANCH}-[a-zA-Z0-9]*/Framework/Devices/did_sdk_server_communication_iOS.framework ${HOME_DIR}/workspace/iOS-DID-SDK_${GIT_BRANCH}-[a-zA-Z0-9]*/Source/DID_Auth_SDK/didm_auth_sdk_iOS/didm_auth_sdk_iOS/external_library/Core/'

        sh 'Echo detectidsdk | rsync --delete -avz -e ssh ${HOME_DIR}/workspace/iOS-Device_${GIT_BRANCH}-[a-zA-Z0-9]*/Framework/Devices/did_sdk_deviceInfo_iOS.framework ${HOME_DIR}/workspace/iOS-DID-SDK_${GIT_BRANCH}-[a-zA-Z0-9]*/Source/DID_Auth_SDK/didm_auth_sdk_iOS/didm_auth_sdk_iOS/external_library/Core/'

        sh 'Echo detectidsdk | rsync --delete -avz -e ssh ${HOME_DIR}/workspace/iOS-Challenge_${GIT_BRANCH}-[a-zA-Z0-9]*/Framework/Devices/did_sdk_challengeotp_ios.framework ${HOME_DIR}/workspace/iOS-DID-SDK_${GIT_BRANCH}-[a-zA-Z0-9]*/Source/DID_Auth_SDK/didm_auth_sdk_iOS/didm_auth_sdk_iOS/external_library/AuthFactors/'
        
        sh 'Echo detectidsdk | rsync --delete -avz -e ssh ${HOME_DIR}/workspace/iOS-Offline_${GIT_BRANCH}-[a-zA-Z0-9]*/Framework/Devices/did_sdk_offline_ios.framework ${HOME_DIR}/workspace/iOS-DID-SDK_${GIT_BRANCH}-[a-zA-Z0-9]*/Source/DID_Auth_SDK/didm_auth_sdk_iOS/didm_auth_sdk_iOS/external_library/AuthFactors/'

        sh 'Echo detectidsdk | rsync --delete -avz -e ssh ${HOME_DIR}/workspace/iOS-Liveness_${GIT_BRANCH}-[a-zA-Z0-9]*/Framework/Liveness.framework ${HOME_DIR}/workspace/iOS-DID-SDK_${GIT_BRANCH}-[a-zA-Z0-9]*/Source/DID_Auth_SDK/didm_auth_sdk_iOS/didm_auth_sdk_iOS/external_library/FaceID/'

        sh 'Echo detectidsdk | rsync --delete -avz -e ssh ${HOME_DIR}/workspace/iOS-FDetector_${GIT_BRANCH}-[a-zA-Z0-9]*/Framework/FaceDetector.framework ${HOME_DIR}/workspace/iOS-DID-SDK_${GIT_BRANCH}-[a-zA-Z0-9]*/Source/DID_Auth_SDK/didm_auth_sdk_iOS/didm_auth_sdk_iOS/external_library/FaceID/'

        sh 'Echo detectidsdk | rsync --delete -avz -e ssh ${HOME_DIR}/workspace/iOS-SelfID_${GIT_BRANCH}-[a-zA-Z0-9]*/Framework/SDK.framework ${HOME_DIR}/workspace/iOS-DID-SDK_${GIT_BRANCH}-[a-zA-Z0-9]*/Source/DID_Auth_SDK/didm_auth_sdk_iOS/didm_auth_sdk_iOS/external_library/FaceID/'
     }
   }
   
    stage('Build') {
        steps {
          dir('Source/DID_Auth_SDK/didm_auth_sdk_iOS') {
            echo 'Building iOS Project'
            sh 'xcodebuild -project didm_auth_sdk_iOS.xcodeproj -scheme didm_auth_sdk_iOS -configuration "Release" clean -destination generic/platform=iOS '
            sh 'xcodebuild -project didm_auth_sdk_iOS.xcodeproj -scheme didm_auth_sdk_iOS -configuration "Release" build ONLY_ACTIVE_ARCH=NO -destination generic/platform=iOS'
          }
        }
      }
            
    stage('Tests') {
      steps {
        dir('Source/DID_Auth_SDK/didm_auth_sdk_iOS') {
          echo 'Testing Project'
          sh 'mkdir -p ../../Framework'
          sh 'rm -rf ../../Reports'
          sh 'xcodebuild -project didm_auth_sdk_iOS.xcodeproj -scheme didm_auth_sdk_iOSTests -configuration "Debug" -destination platform=iOS,name="QA mobile Cyxtera" OTHER_CODE_SIGN_FLAGS="--keychain jenkins-${JOB_NAME}" -enableCodeCoverage YES test'
        }
      }
    }
    
    stage('Compress Artifacts') {
      steps {
        dir('Source/Framework') {
        sh 'zip -r "didm_auth_sdk_iOS.zip" ./*'
        }
      }
    }
    
    stage('CodeCoverage') {
      steps {
        sh 'mkdir -p Source/Reports'
        sh 'chmod 777 Source/Reports'
      }
    }
  }
  post {
    success {
      archiveArtifacts 'Source/Framework/*.zip'
      //junit 'Source/DID_Auth_SDK/didm_auth_sdk_iOS/test_Report.xml'
      script{
          build job: 'iOS-DID-APP/development', parameters: [string(name: 'Name', value: 'Foo1')], quietPeriod: 2, wait: false
      }
      notifyBuildSuccess()
    }
    failure {
      notifyBuildError()
    }
  }
}
def notifyBuildSuccess() {
   emailext (
    // attachmentsPattern: 'Source/Framework/*.zip',
     subject: '${BUILD_STATUS}: [iOS] ${JOB_NAME} Build #${BUILD_NUMBER}',
     body: 'To get the SDK .framework file, please go to the following link and check the Artifacts section, or simply Download it from attachments. You must unzip the file found there: \n ${RUN_DISPLAY_URL}',
     to: 'rafael.bocanegra@cyxtera.com, katerine.vasquez@cyxtera.com, linda.barros@cyxtera.com, elkin.salcedo@cyxtera.com')
}

def notifyBuildError() {
    emailext (
      subject: '${BUILD_STATUS}: [iOS] ${JOB_NAME} Build #${BUILD_NUMBER}',
      body: 'Something went wrong, please check your build log at : \n ${RUN_DISPLAY_URL}',
      to: 'rafael.bocanegra@cyxtera.com, katerine.vasquez@cyxtera.com, linda.barros@cyxtera.com, elkin.salcedo@cyxtera.com')
}
